### PR TITLE
Results on system MI210

### PR DESCRIPTION
**Pull request by zixianwang2022**

### CODE REVIEW

**Comment by zixianwang2022** [comment]
I have filled out the form.

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 this is a test submission right? We'll be cleaning this repository for official results soon.

**Comment by zixianwang2022** [comment]
> Hi @zixianwang2022 this is a test submission right? We'll be cleaning this repository for official results soon.

Yes, this is a test submission. Anything I can do with the failing cla-check?

**Comment by arjunsuresh** [comment]
Cool. The CLA needs to be manually approved by the MLCommons staff. If you have filled the form, please wait for 24 hours.

**Comment by zixianwang2022** [comment]
recheck

**Comment by arjunsuresh** [comment]
Hi @zixianwang2022 finally the CLA is approved :) I'm closing this PR as everything looks fine. Good luck with your competition.

**Pull request closed without merging**
