### PR TITLE
Changes for SCC24

### PR DESCRIPTION
**Pull request by arjunsuresh**

### CODE REVIEW

**Comment by morphine00** [comment]
Hi folks, there are some commits under the name "admin", meaning that one of the users didn't set up their `.git` correctly for GitHub.

**Comment by arjunsuresh** [comment]
Hi Bruno,

This happened because we are using a github action to update some files. Is
there a bot MLCommons email address which we can use for such a purpose?

**Comment by arjunsuresh** [comment]
Hi Bruno,

This happened because we are using a github action to update some files. Is there a bot MLCommons email address which we can use for such a purpose?

**Comment by morphine00** [comment]
Any authorized GitHub acount/token will do. Perhaps this is of help? https://github.com/orgs/community/discussions/25863 .

We can create an account just for this, but at first sight it looks like it's not necessary?

**Comment by arjunsuresh** [comment]
Thank you @morphine00 . I tried to use the [GitHub bot account](https://github.com/orgs/community/discussions/26560) where the user is `actions-user`. But this user still needs to be added in the MLCommons CLA right?

```
Created a committerMap for users in PR: (signed: arjunsuresh-4791823, ) , (notSigned:  admin-, actions-user-65916846, )
MLCommons CLA bot comment id:  2372542209
```

**Comment by morphine00** [comment]
Hi Arjun, in the short term you can have the commits in question authored by you using one of the methods described below, and that'll get you past the CLA bot.

1. However, there's a question raised here: do you foresee the Inference group needing a bot of their own for these actions?

2. Note that regardless of whether you assign attribution of the commits to yourself using the methods below, or we create a bot, those commits and this PR will have to be re-done with the correct attribution. There are methods using Git to retroactively add user information to a commit, but that's generally more work than just redoing the PR.

---

(Options taken from ChatGPT, but it seems to make sense)

A. Signed-off-by Workflow: Ensure that commits made by bots are properly attributed and approved by a human who has signed the licensing agreement. You can implement a "Signed-off-by" footer for each commit, which adds a verifiable trail of human oversight for bot commits. GitHub’s --signoff option can be used when creating commits via bots or CI tools.

B. Co-Authored-by Commit Convention: For commits initiated by bots (such as through GitHub Actions), use the Co-authored-by convention, which allows for multiple authorship attribution. The bot can be listed as the primary author, but the team member who initiated or approved the action can be added as a co-author. This ties the commit back to a specific user who has signed the licensing agreement.

**Comment by arjunsuresh** [comment]
Thank you @morphine00 . I'll take care of updating the commits in this PR. 

But in all CM related repositories we do need a bot to automatically update the README files and also in the inference results repository (during the review period) to update the results summary via github actions. Do you think this `github actions` bot account is fine for this?
https://github.com/orgs/community/discussions/26560

**Comment by nathanwasson** [comment]
Hey @arjunsuresh, following up on this; is there still a need for a bot account for CM? Is your intention to have the bot make commits, open a PR, then have the PR approved and merged, as is this case in this PR, or are you looking to make direct commits to main/master as we've done with the deploy keys?

**Comment by arjunsuresh** [comment]
Hi @nathanw-mlc actually we are still in need of a bot github account for the below 2 use cases.

1. Do automatic update of relevant README files when there is a commit to the main branch in the cm4mlops repository
2. Do automatic update of submission results when there is a commit to the main branch of the inference_results (public) or the submissions_inference (private) repository. 

In both cases the bot account needs to do commit to the same repo and can be done using the deploy keys like we have done previously. But can we use a bot "userid" and "email" for this?

**Comment by nathanwasson** [comment]
> In both cases the bot account needs to do commit to the same repo and can be done using the deploy keys like we have done previously. But can we use a bot "userid" and "email" for this?

@arjunsuresh, is your desire to have a bot userid and email to have the commits attributed to a particular bot account? When a workflow makes commits with a deploy, the commit is automatically attributed to the GitHub account that created the deploy key. We've been using the `mlcommons-bot` account to create the deploy keys, so commits will be attributed to that account. Are you wanting a designated bot account for CM?

**Comment by arjunsuresh** [comment]
Great Nathan. That works for us. So we just need to do the below git config before doing the commit in the github action right?

```
 git config --global user.name mlcommons-bot
 git config --global user.email "mlcommons-bot@users.noreply.github.com"
```

**Comment by nathanwasson** [comment]
> So we just need to do the below git config before doing the commit in the github action right?
> 
> ```
>  git config --global user.name mlcommons-bot
>  git config --global user.email "mlcommons-bot@users.noreply.github.com"
> ```

Yes, that should work, and you only need to use the deploy key when you need to perform actions that need to bypass branch protections.

**Comment by arjunsuresh** [comment]
Thanks a lot Nathan. That solves our problem 😊

**Comment by nathanwasson** [comment]
> That solves our problem

Great, let me know if this solution gives you trouble or needs improvement.

**Pull request merged**
